name: AVL CI
on: [push]
jobs:
  build-plotlib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prescision: [sp, dp]
        os: [linux, macos, windows]
        arch: [x64, aarch64]
        toolchain:
          - {compiler: gcc, version: 11}
          - {compiler: intel-classic, version: "2021.10"}
    steps:
      - uses: actions/checkout@v4
        id: checkout-repo

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: compile plotlib
        run: |
          cd plotlib
          env
          printf "libPlt_%s_%s_%s_%s.a" $FC $FLONUM $OS $BUILDFOR | xargs -I {} make $FC FC=$FC CC=$CC PLTLIB={}
        env:
          BUILDFOR: ${{ matrix.arch }}
          FLONUM: ${{ matrix.prescision }}
          OS: ${{ matrix.os }}
