name: AVL CI
on: [push]
jobs:
  build-plotlib:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        prescision: [sp, dp]
        os: [linux, macos, windows]
        arch: [x86_64, arm64]
        toolchain:
          - {compiler: gcc, version: 11}
          - {compiler: intel-classic, version: "2021.10"}
        exclude:
          - os: windows
            arch: arm64
    steps:
      - uses: actions/checkout@v4
        id: checkout-repo

      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}

      - name: compile plotlib
        run: |
          cd plotlib
          if [ $FLONUM = "dp" ]; then
            printf "%sDP FC=$FC CC=$CC PLTLIB=libPlt_%s_%s_%s_%s.a" $FC $FC $FLONUM $OS $BUILDFOR | xargs make
          else
            printf "%s FC=$FC CC=$CC PLTLIB=libPlt_%s_%s_%s_%s.a" $FC $FC $FLONUM $OS $BUILDFOR | xargs make
          fi
        env:
          BUILDFOR: ${{ matrix.arch }}
          FLONUM: ${{ matrix.prescision }}
          OS: ${{ matrix.os }}

      - uses: actions/upload-artifact@v3
        with:
          name: libPlt_${{ matrix.toolchain.compiler }}_${{ matrix.prescision }}_${{ matrix.os }}_${{ matrix.buildfor }}.a
          path: plotlib/libPlt_${{ matrix.toolchain.compiler }}_${{ matrix.prescision }}_${{ matrix.os }}_${{ matrix.arch }}.a
